// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ESys.Db.DbContext;

namespace ESys.Db.MySQL.Master
{
    [DbContext(typeof(MasterDbContext))]
    partial class MasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ESys.Security.Entity.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<int>("DbType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Limits")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MasterDbConnStr")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SlaveDbConnStr")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tenant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Test",
                            DbType = 0,
                            Limits = new DateTime(2121, 12, 21, 0, 50, 48, 20, DateTimeKind.Utc).AddTicks(1344),
                            MasterDbConnStr = "server=127.0.0.1;database=etestData;user id=root;password=123456;",
                            Name = "Test",
                            SlaveDbConnStr = "server=127.0.0.1;database=etestData;user id=root;password=123456;"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
