// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ESys.Db.DbContext;

namespace ESys.Db.PostgreSQL.Master
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20241210_v0.0.1")]
    partial class v001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ESys.Security.Entity.Tenant", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                b.Property<string>("Code")
                    .HasColumnType("text");

                b.Property<int>("DbType")
                    .HasColumnType("integer");

                b.Property<DateTime>("Limits")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("MasterDbConnStr")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.Property<string>("SlaveDbConnStr")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Tenant");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Code = "Test",
                        DbType = 3,
                        Limits = DateTime.SpecifyKind(new DateTime(2121, 12, 21, 0, 50, 48, 20), DateTimeKind.Unspecified).AddTicks(1344),
                        MasterDbConnStr = "Host=127.0.0.1;Port=5432;Database=etestData;User Id=postgres;Password=123456;",
                        Name = "Test",
                        SlaveDbConnStr = "Host=127.0.0.1;Port=5432;Database=etestData;User Id=postgres;Password=123456;"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
